server.port=8081
spring.application.name=notification-service

spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=reporter
spring.datasource.password=reporter
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
